language: java
install: true
sudo: required
services:
  - docker
jdk:
  - openjdk8
script:
  - "./gradlew versionDisplay"
  - "./gradlew versionFile"
  - "export $(cat build/version.properties | xargs)"
  - "./gradlew build buildImage buildEBArchive"
after_success:
  - "./gradlew jacocoTestReport coveralls"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_deploy:
  - "export ELASTIC_BEANSTALK_LABEL=$VERSION_TAG"
deploy:
  - provider: elasticbeanstalk
    only_create_app_version: "true"
    region: "ap-southeast-2"
    app: "QuickPrint"
    env: "quickprint-pdf"
    bucket_name: "quickprint-eb-deployments"
    skip_cleanup: true
    zip_file: "build/distributions/eb.zip"
    on:
      all_branches: true
      tags: true
  - provider: script
    script: "./gradlew publishImage"
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
