language: java
install: true
sudo: required
services:
  - docker
jdk:
- oraclejdk8
script:
- "./gradlew versionDisplay"
- "./gradlew build createEBArchive"
after_success:
- "./gradlew jacocoTestReport coveralls"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "QuickPrint"
  env: "quickprint-pdf"
  bucket_name: "quickprint-application-versions"
  before_deploy: "./gradlew publishImage"
  skip_cleanup: true
  zip_file: "build/distributions/eb.zip"
  on:
    all_branches: true
    tags: true

#deploy:
#  provider: script
#  script: "./gradlew publishImage"
#  skip_cleanup: true
#  on:
#    all_branches: true
#    tags: true